name: Go CI with PostgreSQL

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.1'  # Target Go 1.23.1

    - name: Install golangci-lint
      run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.54.2

    - name: Install dependencies
      run: go mod download

    - name: Run lint check
      run: make lint
    
    - name: Run tests
      run: make test

    - name: Build project
      run: make build
